name: setup-pnpm
description: "This is a composite GitHub Action that sets up pnpm, node and installs the project's dependencies."
inputs:
  node_version:
    description: "Node.js version"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.5.1

    - name: Setup node ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: pnpm
        registry-url: "https://registry.npmjs.org"

    - name: Restore node_modules
      id: restore-node-modules
      uses: actions/cache/restore@v4
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-{{ inputs.node_version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: install packages
      if: steps.restore-node-modules.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Save node_modules
      id: save-node-modules
      uses: actions/cache/save@v4
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-{{ inputs.node_version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
