name: testing
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Node ${{ matrix.node_version }} testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7.19.0

      - name: install packages
        run: pnpm install

      - name: Build packages
        run: pnpm build
